spring:
    datasource:
        url: jdbc:mysql://localhost:3333/aplicacion_recetas
        username: root
        password: root
    jpa:
        hibernate: 
            ddl-auto: create
        database: mysql
        show-sql: true